analyse sarif file

diff --git a/.github/workflows/import-image.yml b/.github/workflows/import-image.yml
--- a/.github/workflows/import-image.yml
+++ b/.github/workflows/import-image.yml
@@ -40,27 +40,30 @@ jobs:
           uses: aquasecurity/trivy-action@0.24.0
           with:
             image-ref: 'buffdeveloper/vuln-test-image:1.0'
-            format: 'sarif'
+            format: 'json'
             ignore-unfixed: true # ignore vulnerabilities that have no fix
             severity: 'CRITICAL,HIGH'
             scanners: 'vuln'
             exit-code: '0'
-            output: 'trivy-results.sarif'
+            output: 'trivy-results.json'
             trivyignores: 'trivy/.trivyignore'
       
         - name: Install jq
           run: sudo apt-get install -y jq
 
-        - name: Fail if vulnerabilities found
-          if: ${{ steps.trivy.outputs.exit-code == '0' }}
-          run: |
-            # cat trivy-results.sarif
-            if jq -e '.runs[].results[] | select(.properties.severity == "HIGH" or .properties.severity == "CRITICAL")' trivy-results.sarif > /dev/null; then
-            echo "High or critical vulnerabilities found."
-            exit 1
-            else
-              echo "No high or critical vulnerabilities found."
-            fi
+        - name: Analyze SARIF file using jq
+          run: jq -e '.runs[].results[] | select(.properties.severity == "HIGH" or .properties.severity == "CRITICAL")' trivy-results.sarif
+          
+        # - name: Fail if vulnerabilities found
+        #   if: ${{ steps.trivy.outputs.exit-code == '0' }}
+        #   run: |
+        #     # cat trivy-results.sarif
+        #     if jq -e '.runs[].results[] | select(.properties.severity == "HIGH" or .properties.severity == "CRITICAL")' trivy-results.sarif > /dev/null; then
+        #     echo "High or critical vulnerabilities found."
+        #     exit 1
+        #     else
+        #       echo "No high or critical vulnerabilities found."
+        #     fi
 
         - name: Upload Trivy scan results to GitHub Security tab
           uses: github/codeql-action/upload-sarif@v3
