test new command

diff --git a/.github/workflows/import-image.yml b/.github/workflows/import-image.yml
--- a/.github/workflows/import-image.yml
+++ b/.github/workflows/import-image.yml
@@ -40,22 +40,22 @@ jobs:
           uses: aquasecurity/trivy-action@0.24.0
           with:
             image-ref: 'buffdeveloper/vuln-test-image:1.0'
-            format: 'json'
+            format: 'sarif'
             ignore-unfixed: true # ignore vulnerabilities that have no fix
             severity: 'CRITICAL,HIGH'
             scanners: 'vuln'
             exit-code: '0'
-            output: 'trivy-results.json'
+            output: 'trivy-results.sarif'
             trivyignores: 'trivy/.trivyignore'
       
         - name: Install jq
           run: sudo apt-get install -y jq
 
-        # - name: Check for HIGH or CRITICAL vulnerabilities
-        #   id: check_vulnerabilities
-        #   run: |
-        #     jq -e '.runs[].tool.driver.rules[] | select(.properties.tags[2] == "HIGH" or .properties.tags[2] == "CRITICAL")' trivy-results.sarif > /dev/null
-        #   continue-on-error: true
+        - name: Check for HIGH or CRITICAL vulnerabilities
+          id: check_vulnerabilities
+          run: |
+            jq -r '.runs[].results[] | select(.message.text | contains("Severity: HIGH") or contains("Severity: CRITICAL")) | .message.text'
+          continue-on-error: true
     
         # - name: Handle vulnerabilities
         #   if: steps.check_vulnerabilities.outcome == 'success'
@@ -65,17 +65,17 @@ jobs:
         #   if: steps.check_vulnerabilities.outcome != 'success'
         #   run: echo "No high or critical vulnerabilities found."
 
-        - name: Fail if vulnerabilities found
-          if: ${{ steps.trivy.outputs.exit-code == '0' }}
-          run: |
-            cat trivy-results.json | jq -r '.Results[].Vulnerabilities[].VulnerabilityID'
-            # if jq -e '.runs[].tool.driver.rules[] | select(.properties.tags[2] == "HIGH" or .properties.tags[2] == "CRITICAL")' trivy-results.sarif > /dev/null; then
-            #   echo "High or critical vulnerabilities found."
-            # else
-            #   echo "No high or critical vulnerabilities found."
-            #   exit 1
-            # fi
-            # cat trivy-results.json
+        # - name: Fail if vulnerabilities found
+        #   if: ${{ steps.trivy.outputs.exit-code == '0' }}
+        #   run: |
+        #     cat trivy-results.json | jq -r '.Results[].Vulnerabilities[].VulnerabilityID'
+        #     # if jq -e '.runs[].tool.driver.rules[] | select(.properties.tags[2] == "HIGH" or .properties.tags[2] == "CRITICAL")' trivy-results.sarif > /dev/null; then
+        #     #   echo "High or critical vulnerabilities found."
+        #     # else
+        #     #   echo "No high or critical vulnerabilities found."
+        #     #   exit 1
+        #     # fi
+        #     # cat trivy-results.json
 
         # - name: Upload Trivy scan results to GitHub Security tab
         #   uses: github/codeql-action/upload-sarif@v3
