remove exit code

diff --git a/.github/workflows/import-image.yml b/.github/workflows/import-image.yml
--- a/.github/workflows/import-image.yml
+++ b/.github/workflows/import-image.yml
@@ -54,8 +54,8 @@ jobs:
             sarif_file: 'trivy-results.sarif'
             category: 'Container Scanning'
 
-        - name: Fail if vulnerabilities found
-          if: ${{ steps.trivy.outputs.exit-code == '0' }}
-          run: |
-            echo "This image cannot be imported given the critical/high vulnerabilities found"
-            exit 1
+        # - name: Fail if vulnerabilities found
+        #   if: ${{ steps.trivy.outputs.exit-code == '0' }}
+        #   run: |
+        #     echo "This image cannot be imported given the critical/high vulnerabilities found"
+        #     exit 1
