only if critical or high

diff --git a/.github/workflows/import-image.yml b/.github/workflows/import-image.yml
--- a/.github/workflows/import-image.yml
+++ b/.github/workflows/import-image.yml
@@ -32,7 +32,7 @@ jobs:
           with:
             image-ref: 'idealista/prom2teams:4.2.1'
             format: 'sarif'
-            # exit-code: '0'
+            exit-code: '0'
             ignore-unfixed: true # ignore vulnerabilities that have no fix
             severity: 'CRITICAL,HIGH'
             # trivy-config: 'trivy.yaml'
@@ -45,8 +45,8 @@ jobs:
           with:
             sarif_file: 'trivy-results.sarif'
 
-        # - name: Fail if vulnerabilities found
-        #   if: ${{ steps.trivy.outputs.exit-code == '0' }}
-        #   run: |
-        #     echo "This image cannot be imported given the vulnerabilities found"
-        #     exit 1
+        - name: Fail if vulnerabilities found
+          if: ${{ steps.trivy.outputs.exit-code == '0' }}
+          run: |
+            echo "This image cannot be imported given the vulnerabilities found"
+            exit 1
